[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"


[project]
name = "codebase-approx-variant-sampler"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "networkx",
    "dataclasses"
]

[project.scripts]
variant_generator = "variant_generator.generate_variants:main"
post_adapter = "post_adapter.generate_commands:main"
