[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "codebase-approx-variant-sampler"
version = "0.1.0"
requires-python = ">=3.11"

dependencies = [
    "networkx",
    "pandas"
]

[project.scripts]
variant_generator = "variant_generator.generate_variants:main"
post_adapter = "post_adapter.generate_commands:main"
aggregator = "aggregator.consolidate_output:main"

[tool.hatch.build.targets.wheel]
packages = [
    "variant_generator",
    "post_adapter",
    "aggregator"
]